# Проверка статического демо (/v2/) в настоящем браузере: «Сегодня» и недочёты (проход 3), сценарии с главной страницы демо, роли, ссылки, сброс.
# Телефон 390 px (как iPhone), без ошибок в консоли. Скриншоты — docs/screenshots/v2/.
#   python3 scripts/demo-e2e.py [адрес демо]   (по умолчанию https://alexts1516.github.io/sutki-pro-demo/v2/)
# Нужны Python 3 + Playwright и Chrome (CHROME_PATH, по умолчанию /usr/bin/google-chrome).
import os, sys, re, json, struct, zlib
from playwright.sync_api import sync_playwright

B = (sys.argv[1] if len(sys.argv) > 1 else 'https://alexts1516.github.io/sutki-pro-demo/v2/').rstrip('/') + '/'
OUT = os.environ.get('SHOTS_DIR') or os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'docs', 'screenshots', 'v2')
os.makedirs(OUT, exist_ok=True)
CHROME = os.environ.get('CHROME_PATH', '/usr/bin/google-chrome')
errors, passed = [], []

def png_bytes(w=64, h=48, rgb=(200, 80, 40)):
    raw = b''.join(b'\x00' + bytes(rgb) * w for _ in range(h))
    chunk = lambda t, d: struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)
    return b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0)) + chunk(b'IDAT', zlib.compress(raw)) + chunk(b'IEND', b'')

def ok(name):
    passed.append(name); print('  ✓', name)

def check(cond, name):
    if not cond: raise AssertionError(name)
    ok(name)

with sync_playwright() as p:
    br = p.chromium.launch(executable_path=CHROME)
    ctx = br.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, is_mobile=True, has_touch=True, locale='ru-RU', timezone_id='Asia/Almaty',
                         user_agent='Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1')
    pg = ctx.new_page()
    pg.on('console', lambda m: errors.append(f'[console.{m.type}] {m.text} @ {pg.url}') if m.type == 'error' else None)
    pg.on('pageerror', lambda e: errors.append(f'[pageerror] {e} @ {pg.url}'))
    pg.on('dialog', lambda d: d.accept())
    shot = lambda name, full=False: pg.screenshot(path=os.path.join(OUT, name), full_page=full)
    ev = lambda js, arg=None: pg.evaluate(js, arg)
    db = lambda js: pg.evaluate('async () => { const p = SutkiDemo.prisma; ' + js + ' }')

    def overlay_role(title, url_part):
        if pg.locator('#sutki-demo-overlay >> #sheet.on').count(): pg.click('#sutki-demo-overlay >> #close')
        pg.click('#sutki-demo-overlay >> text=Сменить роль')
        pg.click(f'#sutki-demo-overlay >> .role:has-text("{title}")')
        pg.wait_for_url(f'**{url_part}**', timeout=20000)
        pg.wait_for_load_state('networkidle')

    def toast_text(sel='#toasts, #toast'):
        pg.wait_for_timeout(400)
        return ' '.join(pg.locator(sel).all_inner_texts())

    def feed_press(name, extra='KC 852'):
        if pg.locator('#sutki-demo-overlay >> #sheet.on').count(): pg.click('#sutki-demo-overlay >> #close')
        pg.click('#sutki-demo-overlay >> button.tg')
        pg.wait_for_selector('#sutki-demo-overlay >> .msg')
        card = pg.locator('#sutki-demo-overlay >> .msg', has=pg.locator('.kb')).filter(has_text=name).filter(has_text=extra).first
        pg.wait_for_selector('#sutki-demo-overlay >> .toast.on', state='detached', timeout=8000)
        card.locator('.kb button').first.click()
        pg.wait_for_selector('#sutki-demo-overlay >> .toast.on', timeout=10000)
        t = pg.locator('#sutki-demo-overlay >> .toast').inner_text()
        return t

    def feed_pay(*texts):
        if pg.locator('#sutki-demo-overlay >> #sheet.on').count(): pg.click('#sutki-demo-overlay >> #close')
        pg.click('#sutki-demo-overlay >> button.tg')
        pg.wait_for_selector('#sutki-demo-overlay >> .msg')
        card = pg.locator('#sutki-demo-overlay >> .msg', has=pg.locator('.kb'))
        for t in texts: card = card.filter(has_text=t)
        card = card.first
        btn = card.locator('.kb button').first
        label, msg = btn.inner_text(), card.inner_text()
        btn.click()
        pg.wait_for_selector('#sutki-demo-overlay >> .toast.on', timeout=10000)
        return msg, label, pg.locator('#sutki-demo-overlay >> .toast').inner_text()

    # ---------- главная демо ----------
    print('Главная демо:', B)
    pg.goto(B)
    pg.wait_for_function("document.querySelector('#statusText').textContent.includes('Демо готово')", timeout=60000)
    pg.wait_for_function("document.querySelectorAll('#gApt option').length > 5", timeout=20000)
    ok('демо запустилось, данные заполнены сидом (квартир в форме гостя: %d)' % pg.locator('#gApt option').count())
    check(pg.locator('#roles .role').count() == 6, '6 ролей на главной')
    shot('01-landing.png')
    shot('01-landing-full.png', True)

    seed_links = db("const acc = await p.account.findUnique({where:{slug:'astana-stay'}}); const ls = await p.bookingLink.findMany({where:{accountId:acc.id},include:{booking:true}}); return ls.map(l=>({status:l.status, extra:l.extraCheckRequired, submitted:!!l.submittedAt, terms:l.terms, hold:l.booking.holdUntil}));")
    check(len(seed_links)==3 and any(l['status']=='active' and not l['submitted'] for l in seed_links), 'Pass 4 seed: ждём гостя')
    check(any(l['extra'] and l['submitted'] and l['status']=='active' for l in seed_links), 'Pass 4 seed: ждём дополнительное подтверждение')
    check(any(l['status']=='completed' for l in seed_links) and all(l['terms']=='cash_on_arrival' for l in seed_links), 'Pass 4 seed: подтверждённая особая бронь, основной сценарий без залога')
    check(db("return await p.booking.count({where:{status:'confirmed',cleanings:{none:{}}}});")==0, 'Pass 4 seed: confirmed уже имеют подготовку, массовой достройки нет')

    # ---------- проход 3: «Сегодня», недочёты, брони без «подтвердите» ----------
    print('«Сегодня»: исключения первыми, ⚠ недочёты, карточка квартиры, брони без красного «не оплачено»')
    check(db("return await p.booking.count({ where: { source: 'site', status: 'request' } });") == 0, 'в демо-данных нет неоплаченных обычных броней «подтвердите»')
    pg.click('text=Начать: администратор'); pg.wait_for_url('**/admin/**'); pg.wait_for_selector('h1:has-text("Сегодня")')
    pg.wait_for_selector('.op-sec')
    first = pg.locator('#view .op-sec').first
    check('red' in (first.get_attribute('class') or '') and 'Критично' in first.inner_text(), '«Сегодня» начинается с «Критично»: ' + first.locator('.op-p').first.inner_text()[:80])
    td = pg.inner_text('#view')
    check('недочёт' in td.lower() and ('не готова' in td.lower() or 'Решить недочёт' in td), '«Сегодня»: срочный недочёт с подготовки и «квартира не готова» — наверху')
    check('ранний заезд' in td, '«Сегодня»: просьба гостя о раннем заезде → «Согласовать или отказать»')
    shot('pass3-today.png'); shot('pass3-today-full.png', True)
    crit = pg.locator('#view .op[data-open^="apt:"]', has_text='Срочный недочёт').first
    crit.click(); pg.wait_for_selector('.drawer h3:has-text("Недочёты")'); pg.wait_for_timeout(700)
    dr = pg.inner_text('.drawer')
    check(('Почему не готова' in dr or 'Что важно' in dr) and 'Заявка мастеру' in dr and 'Сделаю сам' in dr and 'Решено' in dr, 'карточка квартиры: почему не готова, гости, подготовка, недочёты с кнопками «Заявка мастеру / Сделаю сам / Решено»')
    shot('pass3-apartment-card.png')
    pg.click('.drawer-x')
    pg.goto(B + 'admin/#calendar'); pg.wait_for_selector('.agenda, .cal'); pg.wait_for_timeout(400)
    check('⚠' in pg.inner_text('#view'), 'календарь: на плитке подготовки — ⚠N (недочёты), а не просто «готово»')
    shot('pass3-calendar.png')
    pg.goto(B + 'admin/#bookings'); pg.wait_for_selector('h1:has-text("Брони")'); pg.wait_for_timeout(300)
    bv = pg.inner_text('#view')
    check(pg.locator('#view .chip.red').count() == 0 and 'Не оплачено' not in bv and 'Подтвердить' not in bv, 'брони: нет красных «не оплачено» и кнопок «Подтвердить»; оплата — «оплачено на сайте» / «наличные при заезде» / «залог»')
    shot('pass3-bookings.png')

    # ---------- сценарий 1: гость бронирует и оплачивает → водитель ----------
    print('Сценарий 1: бронь с оплатой на сайте → заказ водителям → «Беру» → «Запланировано» → шаги → деньги')
    pg.goto(B); pg.wait_for_function("document.querySelector('#statusText').textContent.includes('Демо готово')")
    pg.wait_for_function("document.querySelectorAll('#gApt option').length > 5")
    pg.click('#gBtn'); pg.wait_for_selector('#gRes .ok, #gRes .err')
    check(pg.locator('#gRes .ok').count() == 1 and 'подтверждена автоматически' in pg.inner_text('#gRes'), 'гость забронировал и оплатил на сайте → бронь подтверждена сама: ' + pg.inner_text('#gRes').split('\n')[0][:90])
    shot('02-guest-paid.png')
    bk = db("const b = await p.booking.findFirst({ where: { guest: { name: 'Анна Смирнова' } }, orderBy: { createdAt: 'desc' } }); return { id: b.id, number: b.number, status: b.status, pay: b.paymentStatus };")
    job = db(f"const j = await p.transferJob.findFirst({{ where: {{ bookingId: '{bk['id']}' }} }}); return {{ id: j.id, status: j.status }};")
    check(bk['status'] == 'confirmed' and bk['pay'] == 'paid' and job['status'] == 'OFFERED', f'бронь №{bk["number"]} оплачена и подтверждена → заказ водителям OFFERED')
    pg.click('#sutki-demo-overlay >> button.tg'); pg.wait_for_selector('#sutki-demo-overlay >> .msg')
    n_offers = pg.locator('#sutki-demo-overlay >> .kb button').count()
    check(n_offers >= 3, f'в «Telegram (демо)» у водителей предложения с кнопкой «Беру» ({n_offers})')
    shot('03-telegram-offers.png')
    pg.click('#sutki-demo-overlay >> #close')
    t = feed_press('Руслан')
    check('Заказ ваш' in t, 'Руслан нажал «Беру» в Telegram (демо) → «Заказ ваш ✅»')
    pg.wait_for_timeout(1800)  # панель перезагружает страницу
    t2 = feed_press('Бауыржан')
    print('    t2=', t2[:200]); check('Уже взял другой' in t2, 'второй водитель → «Уже взял другой водитель» (первый получает заказ)')
    shot('04-telegram-taken.png')
    pg.wait_for_timeout(1800)
    j = db(f"const j = await p.transferJob.findUnique({{ where: {{ id: '{job['id']}' }}, include: {{ driverUser: true }} }}); return {{ status: j.status, driver: j.driverUser?.name }};")
    check(j['status'] == 'ACCEPTED' and j['driver'].startswith('Руслан'), 'заказ ACCEPTED у Руслана')
    # чужой водитель не видит квартиру и телефон, а оплату гостя — никто из водителей
    other = ev("""async (id) => { await SutkiDemo.login('bauyrzhan@astanastay.example'); const r = await fetch('/api/staff/transfers/' + id); const j = await r.json();
      const acc = await fetch('/api/staff/transfers/' + id + '/accept', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); return { j, acc: acc.status }; }""", job['id'])
    check(not other['j'].get('guestPhone') and not (other['j'].get('apartment') or {}).get('apartmentNumber') and other['acc'] == 409, 'другой водитель: без телефона и номера квартиры, «Беру» → 409')
    overlay_role('Водитель Руслан', '/app/')
    pg.wait_for_selector('text=Мои поездки')
    pg.wait_for_timeout(500); lst = pg.inner_text('#view'); shot('pass3-driver-list.png'); shot('pass3-driver-list-full.png', True)
    check('Запланировано' in lst and any(w in lst.lower() for w in ('сегодня', 'завтра', 'позже')), 'список водителя: по времени подачи, группы «Сегодня / Завтра / Позже», будущая поездка — «Запланировано · через N дн.»')
    pg.click(f'[data-tr="{job["id"]}"]'); pg.wait_for_selector('#sheet:not([hidden]) .sheet-body'); pg.wait_for_timeout(300)
    check(pg.locator('[data-act="en-route"], [data-act="arrived"], [data-act="picked-up"], [data-act="done"]').count() == 0 and 'появится' in pg.inner_text('#sheet'), 'будущая поездка: кнопок шагов нет — «Выехал» появится за 2 ч до подачи')
    shot('pass3-driver-planned.png')
    early = ev("async (id) => { const r = await fetch('/api/staff/transfers/' + id + '/en-route', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{\"etaMinutes\":20}' }); return { s: r.status, e: (await r.json()).error }; }", job['id'])
    check(early['s'] == 409 and 'Рано' in early['e'], 'нажать «Выехал» за несколько дней нельзя и через API: ' + early['e'][:70])
    # подача через час — окно открыто
    db(f"await p.transferJob.update({{ where: {{ id: '{job['id']}' }}, data: {{ pickupAt: new Date(Date.now() + 3600000) }} }}); return 1;"); pg.wait_for_timeout(900)
    pg.reload(); pg.wait_for_selector('text=Мои поездки')
    pg.click(f'[data-tr="{job["id"]}"]'); pg.wait_for_selector('[data-act="en-route"]')
    check(pg.locator('[data-act="arrived"], [data-act="picked-up"], [data-act="done"]').count() == 0, 'за час до подачи — только следующий шаг «Выехал» (строго по порядку)')
    body = pg.inner_text('body')
    check('Квартира' in body and '№' in body and 'Телефон' in body, 'после «Беру» Руслан видит номер квартиры и телефон гостя')
    shot('05-driver-trip.png')
    pg.click('[data-act="en-route"]'); pg.click('[data-eta="20"]'); pg.wait_for_selector('[data-act="arrived"]')
    pg.click('[data-act="arrived"]'); pg.wait_for_selector('[data-act="picked-up"]')
    pg.click('[data-act="picked-up"]'); pg.wait_for_selector('[data-act="done"]')
    shot('06-driver-steps.png')
    pg.click('[data-act="done"]'); pg.wait_for_timeout(800)
    st = db(f"return (await p.transferJob.findUnique({{ where: {{ id: '{job['id']}' }}, include: {{ payoutRecord: true }} }}));")
    check(st['status'] == 'DONE' and st['payoutRecord'] and st['payoutRecord']['status'] == 'PENDING', 'шаги «Выехал → На месте → Гость в машине → Завершить» → DONE, долг водителю PENDING')
    drv = ev("async (id) => (await (await fetch('/api/staff/transfers/' + id)).json())", job['id'])
    check('guestPayment' not in json.dumps(drv) and 'priceKzt' not in drv, 'водитель не видит оплату гостя и цену для гостя')
    overlay_role('Владелец Азамат', '/admin/')
    pg.goto(B + f'admin/#transfers/{job["id"]}'); pg.wait_for_selector('text=Оплата гостя → бизнес')
    pg.click('[data-act="gpaid"][data-m="cash"]'); pg.wait_for_function("document.querySelector('#toasts').innerText.includes('доход бизнеса')")
    pg.click('[data-act="paid"]'); pg.wait_for_function("document.querySelector('#toasts').innerText.includes('выплачено водителю')")
    pg.wait_for_timeout(400)
    pg.locator('text=Оплата гостя → бизнес').scroll_into_view_if_needed()
    shot('07-owner-transfer-money.png')
    money = db(f"const j = await p.transferJob.findUnique({{ where: {{ id: '{job['id']}' }}, include: {{ transfer: true, payoutRecord: true }} }}); return {{ g: j.transfer.guestPaymentStatus, m: j.transfer.guestPaymentMethod, pr: j.payoutRecord.status, by: j.payoutRecord.paidByName }};")
    check(money == {'g': 'PAID', 'm': 'cash', 'pr': 'PAID', 'by': money['by']} and money['by'], 'оплата гостя → бизнес (наличные) записана, выплата водителю PAID с тем, кто отметил')

    # ---------- сценарий 2: заявка мастеру ----------
    print('Сценарий 2: заявка мастеру → смета по фото → одобрить → доп. расход → выполнено')
    pg.goto(B); pg.wait_for_function("document.querySelector('#statusText').textContent.includes('Демо готово')")
    pg.click('text=Начать: новая заявка'); pg.wait_for_url('**/admin/**'); pg.wait_for_selector('#wrForm')
    pg.fill('#wrForm [name=title]', 'Не работает розетка у кровати')
    pg.fill('#wrForm [name=description]', 'Искрит и не держит вилку, фото приложу')
    opt = pg.locator('#wrForm [name=executor] option', has_text='Master Electric').first.get_attribute('value')
    pg.select_option('#wrForm [name=executor]', opt)
    pg.select_option('#wrForm [name=type]', 'elec')
    shot('08-owner-new-repair.png')
    pg.click('#wrCreate'); pg.wait_for_function("location.hash.startsWith('#repairs/') && location.hash !== '#repairs/new'")
    rid = pg.evaluate("location.hash.split('/')[1]")
    pg.set_input_files('#wrPh', files=[{'name': 'rozetka.png', 'mimeType': 'image/png', 'buffer': png_bytes()}])
    pg.wait_for_function("document.querySelector('#toasts').innerText.includes('Фото добавлены')")
    r = db(f"return await p.repairTask.findUnique({{ where: {{ id: '{rid}' }}, include: {{ photos: true }} }});")
    check(r['status'] == 'NEW' and len(r['photos']) == 1, 'заявка создана, фото проблемы загружено (хранится в браузере)')
    overlay_role('Мастер Master Electric', '/app/')
    pg.click('[data-tab="repairs"]') if pg.locator('[data-tab="repairs"]').count() else None
    pg.click(f'[data-wr="{rid}"]'); pg.wait_for_selector('[data-wact="estimate:PHOTOS"]')
    pg.click('[data-wact="estimate:PHOTOS"]')
    pg.fill('#wrForm [name=labourKzt]', '8000'); pg.fill('#wrForm [name=items]', 'Замена розетки, проверка линии')
    shot('09-master-estimate.png')
    pg.click('#wrForm button.primary'); pg.wait_for_timeout(800)
    check(db(f"return (await p.repairTask.findUnique({{ where: {{ id: '{rid}' }} }})).status;") == 'AWAITING_OWNER_APPROVAL', 'мастер отправил смету по фото → «Ждёт одобрения сметы»')
    st = ev("async (id) => { const r = await fetch('/api/staff/repairs/' + id + '/start', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); return r.status; }", rid)
    check(st == 409 or st == 400 or st == 403, f'начать работу без одобрения нельзя ({st})')
    overlay_role('Владелец Азамат', '/admin/')
    pg.goto(B + f'admin/#repairs/{rid}'); pg.wait_for_selector('[data-est-ok]')
    pg.click('[data-est-ok]'); pg.wait_for_function("document.querySelector('#toasts').innerText.includes('Смета одобрена')")
    ok('владелец одобрил смету')
    overlay_role('Мастер Master Electric', '/app/')
    pg.click('[data-tab="repairs"]') if pg.locator('[data-tab="repairs"]').count() else None
    pg.click(f'[data-wr="{rid}"]'); pg.wait_for_selector('[data-wact="start"]')
    pg.click('[data-wact="start"]'); pg.wait_for_selector('[data-wact="extra"]')
    sheet_txt = pg.inner_text('#sheet') if pg.locator('#sheet').count() else pg.inner_text('body')
    r = db(f"return await p.repairTask.findUnique({{ where: {{ id: '{rid}' }} }});")
    check(r['status'] == 'IN_PROGRESS' and r['startedAt'] and not r['doneAt'] and 'В работе' in sheet_txt and 'Завершить работу' in sheet_txt and 'Работа выполнена' not in sheet_txt,
          '«Начать работу» → «🔧 В работе с …» и отдельная кнопка «Завершить работу» (не «выполнена»), время начала записано')
    shot('10a-master-in-progress.png')
    pg.click('[data-wact="extra"]')
    pg.fill('#wrForm [name=amountKzt]', '3000'); pg.fill('#wrForm [name=description]', 'Заменить подрозетник'); pg.fill('#wrForm [name=reason]', 'Старый подрозетник оплавлен')
    pg.click('#wrForm button.primary'); pg.wait_for_timeout(800)
    check(db(f"return (await p.extraExpense.findFirst({{ where: {{ repairTaskId: '{rid}' }} }})).status;") == 'PENDING', 'мастер начал работу и добавил доп. расход 3 000 ₸ → ждёт решения')
    shot('10-master-extra.png')
    overlay_role('Владелец Азамат', '/admin/')
    pg.goto(B + f'admin/#repairs/{rid}'); pg.wait_for_selector('[data-x-ok]')
    pg.click('[data-x-ok]'); pg.wait_for_function("document.querySelector('#toasts').innerText.includes('Доп. расход одобрен')")
    ok('владелец одобрил доп. расход')
    overlay_role('Мастер Master Electric', '/app/')
    pg.click('[data-tab="repairs"]') if pg.locator('[data-tab="repairs"]').count() else None
    pg.click(f'[data-wr="{rid}"]'); pg.wait_for_selector('[data-wact="complete"]')
    check('Завершить работу' in pg.locator('[data-wact="complete"]').inner_text(), 'кнопка «🏁 Завершить работу»')
    pg.click('[data-wact="complete"]'); pg.fill('#wrForm [name=report]', 'Заменил розетку и подрозетник, проверил — работает')
    pg.click('#wrForm button.primary'); pg.wait_for_timeout(900)
    r = db(f"return await p.repairTask.findUnique({{ where: {{ id: '{rid}' }} }});")
    check(r['status'] == 'DONE' and r['costKzt'] == 11000, f'«Выполнено» → DONE, сумма для финансов {r["costKzt"]} ₸ (смета 8 000 + доп. 3 000)')
    check(r['doneAt'] and r['startedAt'] and r['doneAt'] >= r['startedAt'], 'записаны время начала и окончания работы')
    shot('11-master-done.png')
    po = db(f"return await p.payout.findFirst({{ where: {{ repairTaskId: '{rid}' }} }});")
    check(po and po['status'] == 'PENDING' and po['amountKzt'] == 11000, 'выплата мастеру создана сразу: «К оплате» 11 000 ₸')
    msg, label, t = feed_pay('Master Electric', 'к оплате')
    check('11 000' in msg and 'Оплатить' in label and 'ыплачено' in t, f'владельцу в Telegram: «{[l for l in msg.splitlines() if 'оплате' in l][0][:90]}…» → «{label}» → «{t}»')
    shot('11a-telegram-payout.png')
    pg.wait_for_timeout(1800)
    po = db(f"return await p.payout.findFirst({{ where: {{ repairTaskId: '{rid}' }} }});")
    rp = db(f"return (await p.repairTask.findUnique({{ where: {{ id: '{rid}' }} }})).paid;")
    check(po['status'] == 'PAID' and po['method'] and rp, 'выплата отмечена (PAID, способ записан), заявка — «оплачено»')

    # ---------- сценарий 3: комиссия → финансы ----------
    print('Сценарий 3: настройки комиссии → финансы')
    overlay_role('Владелец Азамат', '/admin/')
    pg.goto(B + 'admin/#settings'); pg.wait_for_selector('#stForm')
    pg.check('#stForm [name=transferPayoutMode][value=PERCENT]')
    pg.fill('#stForm [name=ownerCommissionPercent]', '20')
    check(pg.is_checked('#stForm [name=ownerDrivesKeepsAll]'), 'настройка «Везёт сам владелец — вся сумма бизнесу» включена по умолчанию')
    pg.click('#stForm button.primary'); pg.wait_for_timeout(700)
    s = db("return await p.accountSettings.findFirst({ where: { account: { slug: 'astana-stay' } } });")
    check(s['transferPayoutMode'] == 'PERCENT' and s['ownerCommissionPercent'] == 20, 'комиссия 20% сохранена')
    pg.locator('#stForm').scroll_into_view_if_needed(); shot('12-owner-settings.png')
    # новая поездка после настройки: водителю 80%
    pv = ev("""async () => { const r = await fetch('/api/public/astana-stay/transfers', { method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ direction: 'in', place: 'airport', date: new Date(Date.now() + 2 * 864e5).toISOString().slice(0, 10), time: '11:00', name: 'Тест Гость', phone: '+77015550000' }) });
      const t = await r.json(); const d = await fetch('/api/admin/transfers/' + t.id + '/dispatch', { method: 'POST' }); const j = await d.json(); return { price: t.priceKzt, payout: j.payoutKzt, commission: j.commissionKzt }; }""")
    check(pv['payout'] == round(pv['price'] * 0.8 / 100) * 100 and pv['commission'] == pv['price'] - pv['payout'], f'новый заказ: водителю {pv["payout"]} из {pv["price"]} ₸ (комиссия 20%)')
    pg.goto(B + 'admin/#finance'); pg.wait_for_selector('h1:has-text("Финансы")'); pg.wait_for_timeout(500)
    fin = pg.inner_text('#view')
    check('Трансферы' in fin and 'Выручка' in fin, 'финансы: выручка трансферов, выплаты водителям, маржа')
    shot('13-owner-finance.png'); shot('13-owner-finance-full.png', True)
    # администратор не видит финансы
    overlay_role('Администратор Алина', '/admin/')
    pg.wait_for_selector('#nav button')
    check(pg.locator('#nav [data-nav="finance"]').count() == 0, 'администратор: раздела «Финансы» нет')

    # ---------- остальные роли и ссылки ----------
    print('Роли и ссылки без входа')
    print('Подготовка квартиры → выплата → полный отчёт в календаре')
    cl = db("const u = await p.user.findFirst({ where: { email: 'gulnara@astanastay.example' } }); const today = new Date(new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Almaty' }) + 'T00:00:00Z'); const t = await p.cleaningTask.findFirst({ where: { assigneeId: u.id, status: { in: ['assigned', 'enroute'] }, date: { lte: today } }, orderBy: { date: 'desc' } }); return { id: t.id, date: t.date };")
    fut = db("const u = await p.user.findFirst({ where: { email: 'gulnara@astanastay.example' } }); const today = new Date(new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Almaty' }) + 'T00:00:00Z'); const t = await p.cleaningTask.findFirst({ where: { assigneeId: u.id, status: 'assigned', date: { gt: today } } }); return t && t.id;")
    overlay_role('Подготовка — Гульнара', '/app/'); pg.wait_for_selector('#view'); pg.wait_for_timeout(500)
    check('Гульнара' in pg.inner_text('#who') and 'Подготовка' in pg.inner_text('body') and '⏰' in pg.inner_text('#view'), 'специалист по подготовке: сверху «Сейчас» — квартира, адрес и срок'); shot('14-cleaner.png')
    if fut:
        st = ev("async (id) => (await fetch('/api/staff/cleaning/' + id + '/start', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status", fut)
        check(st == 409, 'подготовку на другой день начать заранее нельзя (409)')
    pg.click(f'[data-cl="{cl["id"]}"]'); pg.wait_for_selector('[data-go="start"]')
    pg.click('[data-go="start"]'); pg.wait_for_selector('[data-ck]')
    n = pg.locator('[data-ck]').count()
    pg.click('[data-go="finish"]'); pg.wait_for_timeout(700)
    check(db(f"return (await p.cleaningTask.findUnique({{ where: {{ id: '{cl['id']}' }} }})).status;") == 'progress', 'закончить с неотмеченными пунктами без комментария нельзя')
    for i in range(n):
        pg.locator(f'[data-ck="{i}"]').check(); pg.wait_for_timeout(350)
    pg.set_input_files('[data-ph="0"]', files=[{'name': 'bed.png', 'mimeType': 'image/png', 'buffer': png_bytes(rgb=(60, 140, 200))}]); pg.wait_for_timeout(700)
    pg.click('[data-go="problem"]'); pg.fill('#clForm [name=text]', 'Перегорела лампа в коридоре'); pg.check('#clForm [name=priority][value=urgent]'); pg.click('#clForm button.primary'); pg.wait_for_timeout(800)
    pg.fill('#clRep', 'Всё готово, лампу надо заменить'); shot('14a-cleaner-checklist.png', True)
    pg.click('[data-go="finish"]'); pg.wait_for_timeout(900)
    c = db(f"return await p.cleaningTask.findUnique({{ where: {{ id: '{cl['id']}' }}, include: {{ payout: true, photos: true }} }});")
    dfc = db(f"return await p.defect.findMany({{ where: {{ cleaningTaskId: '{cl['id']}' }} }});")
    check(c['status'] == 'done' and c['startedAt'] and c['doneAt'] and len(c['photos']) >= 1 and len(dfc) == 1 and dfc[0]['priority'] == 'urgent' and dfc[0]['status'] == 'open', f'чек-лист {n} пунктов отмечен, фото и срочный недочёт (висит, пока не решат), «Закончить» → время начала и окончания записаны')
    check(c['payout'] and c['payout']['status'] == 'PENDING' and c['payout']['amountKzt'] > 0, f'выплата за подготовку создана сразу: к оплате {c["payout"]["amountKzt"]} ₸')
    msg, label, t = feed_pay('Гульнара', 'к оплате', 'подготовк')
    check('Оплатить' in label and 'ыплачено' in t, f'владельцу: «{[l for l in msg.splitlines() if 'оплате' in l][0][:90]}» → «{label}» → «{t}»')
    pg.wait_for_timeout(1800)
    pg.click('[data-tab="payouts"]'); pg.wait_for_timeout(500)
    check('Выплачено' in pg.inner_text('#view'), 'специалист видит свои выплаты «К оплате / Выплачено» с датами'); shot('14b-cleaner-payouts.png')
    overlay_role('Владелец Азамат', '/admin/')
    pg.goto(B + 'admin/#calendar'); pg.wait_for_selector(f'[data-open="cl:{cl["id"]}"]', timeout=15000)
    pg.locator(f'[data-open="cl:{cl["id"]}"]').first.click(); pg.wait_for_selector('text=Чек-лист')
    pg.wait_for_timeout(400); shot('14c-owner-cleaning-report.png')
    dr = pg.evaluate("document.body.textContent")
    if os.environ.get('DEBUG'): print(dr[-3000:])
    check(all(x in dr for x in ['Гульнара', 'Начало', 'Окончание', 'Чек-лист', 'Недочёты', 'Перегорела лампа', 'ыплачено']), 'календарь: плитка подготовки (⚠) открывает полный отчёт на месте (кто, начало/окончание, чек-лист, фото, недочёты, выплата)')
    pg.click('.drawer-x'); pg.goto(B + 'admin/#today'); pg.wait_for_selector('h1:has-text("Сегодня")'); pg.wait_for_timeout(400)
    check('Перегорела лампа' in pg.inner_text('#view'), '«Сегодня»: недочёт с подготовки виден сразу')
    pg.goto(B + 'admin/#calendar'); pg.wait_for_selector(f'[data-open="cl:{cl["id"]}"]', timeout=15000)
    pg.locator(f'[data-open="cl:{cl["id"]}"]').first.click(); pg.wait_for_selector('text=Чек-лист')
    pg.click('[data-df^="repair:"]'); pg.wait_for_selector('#drawer #wrAssign', timeout=10000)
    check('Перегорела лампа' in pg.inner_text('#drawer'), 'недочёт → «Заявка мастеру» одним нажатием (заявка без мастера, можно выбрать)')
    df = db(f"const d = await p.defect.findFirst({{ where: {{ cleaningTaskId: '{cl['id']}', text: {{ contains: 'Перегорела лампа' }} }} }}); return {{ id: d.id, repair: d.repairTaskId, status: d.status }};")
    neg = ev("""async (id) => { const post = (u) => fetch(u, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }).then(async r => ({ s: r.status, b: await r.json() }));
      const [a, b] = await Promise.all([post('/api/admin/defects/' + id + '/repair'), post('/api/admin/defects/' + id + '/repair')]);
      const res = await post('/api/admin/defects/' + id + '/resolve'); return { a: a.b.repairTaskId, b: b.b.repairTaskId, res: res.s }; }""", df['id'])
    check(neg['a'] == neg['b'] == df['repair'] and neg['res'] == 409 and df['status'] == 'open', 'повторная «Заявка мастеру» — та же заявка; «Решено» до работы мастера — запрещено (409), недочёт открыт')
    pg.goto(B + 'admin/#payouts'); pg.wait_for_selector('h1:has-text("Выплаты")'); pg.wait_for_timeout(500)
    check('К оплате' in pg.inner_text('#view') or 'должны' in pg.inner_text('#view'), 'экран «Выплаты»: кому сколько должны'); shot('14d-owner-payouts.png')
    overlay_role('Внешний мастер по ссылке', '/link/'); pg.wait_for_timeout(900)
    check('Ссылка недействительна' not in pg.inner_text('#view'), 'внешний мастер открывает заявку по ссылке без входа'); shot('16-external-master-link.png')

    # ---------- личная ссылка гостя (проход 4, шаг 7): без входа, предложение → данные → согласие → «Подтвердить» ----------
    print('Личная ссылка гостя (вид special): подтверждение и истёкшая ссылка')
    overlay_role('Владелец Азамат', '/admin/')
    mk_link = """async (off) => { const a = await SutkiDemo.prisma.apartment.findFirst({ where: { active: true, accountId: (await SutkiDemo.prisma.account.findUnique({ where: { slug: 'astana-stay' } })).id }, orderBy: { sortOrder: 'asc' } });
      const day = (n) => new Date(Date.now() + n * 864e5).toISOString().slice(0, 10);
      const r = await fetch('/api/admin/booking-links', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ apartmentId: a.id, checkIn: day(off), checkOut: day(off + 2), guestsCount: 2, terms: 'cash_on_arrival', note: 'Договорились в WhatsApp' }) });
      const j = await r.json(); return { s: r.status, token: (j.url || '').split('/link/')[1]?.replace(/^#/, ''), bookingId: j.link?.bookingId, title: a.title, address: a.address, err: j.error }; }"""
    sl = ev(mk_link, 300)
    check(sl['s'] == 201 and len(sl['token'] or '') == 43, 'владелец создал личную ссылку (демо): ' + str(sl.get('err') or 'токен 43 символа'))
    conflict = ev(mk_link, 300)
    check(conflict['s'] == 409 and not conflict.get('bookingId'), 'E2E конфликт дат: вторая личная ссылка на удерживаемые даты не создаётся (409)')
    pg.goto(B + 'link/#' + sl['token']); pg.wait_for_selector('#spSubmit', timeout=20000); pg.wait_for_timeout(300)
    t = pg.inner_text('#view')
    check(all(x in t for x in [sl['title'], 'Предложение действует до', 'Оплата наличными при заезде', 'Договорились в WhatsApp', 'Ночей']) and sl['address'].split(',')[0] not in t,
          'гость без входа видит предложение: квартира, даты, сумма, условия, срок; адреса до подтверждения нет')
    shot('18-special-link-offer.png', True)
    pg.click('#spSubmit'); pg.wait_for_selector('#spErr:not([hidden])')
    check('имя и телефон' in pg.inner_text('#spErr'), 'без имени и телефона — понятная подсказка, запроса нет')
    pg.fill('#spName', 'Гость Ссылки'); pg.fill('#spPhone', '+7 701 555 66 77'); pg.click('#spSubmit'); pg.wait_for_timeout(200)
    check('согласие' in pg.inner_text('#spErr'), 'без галочки «Согласен» — понятная подсказка, запроса нет')
    pg.check('#spTerms')
    ev("() => { const b = document.querySelector('#spSubmit'); b.click(); b.click(); b.click(); }")   # тройное нажатие — один запрос
    pg.wait_for_selector('[data-state="confirmed"]', timeout=20000); pg.wait_for_timeout(300)
    t = pg.inner_text('#view')
    nprep = db(f"return await p.cleaningTask.count({{ where: {{ bookingId: '{sl['bookingId']}' }} }});")
    st = db(f"const b = await p.booking.findUnique({{ where: {{ id: '{sl['bookingId']}' }} }}); const l = await p.bookingLink.findUnique({{ where: {{ bookingId: b.id }} }}); return [b.status, l.status, b.number];")
    check(st[0] == 'confirmed' and st[1] == 'completed' and nprep == 1 and f'Бронь №{st[2]} подтверждена' in t and sl['address'] in t,
          f'«Подтвердить» → бронь №{st[2]} подтверждена, ссылка завершена, одна подготовка (тройное нажатие); адрес показан')
    shot('19-special-link-confirmed.png', True)
    pg.reload(); pg.wait_for_selector('[data-state="confirmed"]', timeout=20000)
    check(f'Бронь №{st[2]} подтверждена' in pg.inner_text('#view'), 'обновление страницы — то же состояние с сервера')
    ex = ev(mk_link, 310)
    db(f"await p.booking.update({{ where: {{ id: '{ex['bookingId']}' }}, data: {{ holdUntil: new Date(Date.now() - 1000) }} }}); return 1;")
    pg.wait_for_timeout(800)   # демо сохраняет изменения через 400 мс
    pg.goto(B + 'link/#' + ex['token']); pg.wait_for_selector('[data-state="expired"]', timeout=20000)
    stx = db(f"const b = await p.booking.findUnique({{ where: {{ id: '{ex['bookingId']}' }} }}); const l = await p.bookingLink.findUnique({{ where: {{ bookingId: b.id }} }}); return [b.status, l.status];")
    check('Срок предложения истёк' in pg.inner_text('#view') and stx == ['cancelled', 'expired'], 'истёкшая ссылка: «Срок предложения истёк», бронь отменена, даты свободны')
    shot('20-special-link-expired.png')
    dl = ev(mk_link.replace("terms: 'cash_on_arrival'", "terms: 'deposit', depositKzt: 10000"), 320)
    pg.goto(B + 'link/#' + dl['token']); pg.wait_for_selector('#spSubmit', timeout=20000)
    pg.fill('#spName', 'Гость Залог'); pg.fill('#spPhone', '+7 701 555 66 78'); pg.check('#spTerms'); pg.click('#spSubmit')
    pg.wait_for_selector('[data-state="waiting_deposit"]', timeout=20000)
    check('Ждём, когда владелец отметит залог' in pg.inner_text('#view') and db(f"return (await p.booking.findUnique({{ where: {{ id: '{dl['bookingId']}' }} }})).status;") == 'request',
          'ссылка с залогом: после «Подтвердить» — «Ждём, когда владелец отметит залог» (не ошибка), бронь ещё не подтверждена')
    shot('21-special-link-waiting-deposit.png', True)
    lid = db(f"return (await p.bookingLink.findUnique({{ where: {{ bookingId: '{dl['bookingId']}' }} }})).id;")
    rv = ev("async (id) => (await fetch('/api/admin/booking-links/' + id + '/revoke', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status", lid)
    pg.reload(); pg.wait_for_selector('[data-state="revoked"]', timeout=20000)
    check(rv == 200 and 'Ссылка отозвана' in pg.inner_text('#view'), 'отозванная ссылка — «Ссылка отозвана»')
    overlay_role('Владелец Азамат', '/admin/')
    extra = ev(mk_link.replace("terms: 'cash_on_arrival'", "terms: 'cash_on_arrival', extraCheckRequired: true, extraCheckNote: 'Позвоните владельцу'"), 330)
    pg.goto(B+'link/#'+extra['token']); pg.wait_for_selector('#spSubmit'); pg.fill('#spName','Гость подтверждения'); pg.fill('#spPhone','+77015556679'); pg.check('#spTerms'); pg.click('#spSubmit')
    pg.wait_for_selector('[data-state="waiting_extra_check"]')
    check('Позвоните владельцу' in pg.inner_text('#view'), 'доп. подтверждение: гость завершил свою часть, ждёт менеджера без загрузки документов')
    check(ev("async id => {const r=await fetch('/api/admin/today');const j=await r.json();return j.items.some(i=>i.kind==='link_waiting_admin'&&i.ref===id);}",extra['bookingId']), 'Сегодня: гость завершил свою часть, требуется действие менеджера')
    pg.screenshot(path=os.path.join(OUT,'22-special-waiting-admin.png'),full_page=True)
    lid=db(f"return (await p.bookingLink.findUnique({{where:{{bookingId:'{extra['bookingId']}'}}}})).id;")
    rc=ev("async id => (await fetch('/api/admin/booking-links/'+id+'/extra-check',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status",lid)
    pg.reload(); pg.wait_for_selector('[data-state="confirmed"]')
    check(rc==200 and extra['address'] in pg.inner_text('#view'),'отметка менеджера автоматически подтверждает, адрес показан')
    prep=db(f"return await p.cleaningTask.findFirst({{where:{{bookingId:'{extra['bookingId']}'}}}});")
    check(bool(prep), 'счастливый путь: обязательная подготовка сохранена')
    overlay_role('Владелец Азамат','/admin/')
    pg.get_by_role('button',name='Меню',exact=True).click()
    pg.click('nav button:has-text("Календарь")'); pg.wait_for_timeout(600)
    # API календаря проверяет присутствие реальной подготовки даже вне текущего окна на экране.
    cal=ev("async r => { const x=await fetch('/api/admin/calendar?from='+r[0]+'&to='+r[1]);return x.json(); }",[str(prep['date'])[:10],str(prep['date'])[:10]])
    check(str(prep['id']) in str(cal), 'подготовка особой брони доступна в календаре')

    pg.goto(B + 'link/#' + 'x' * 43); pg.wait_for_selector('#view .card', timeout=20000); pg.wait_for_timeout(300)
    check('Ссылка недействительна' in pg.inner_text('#view'), 'неверная личная ссылка — «Ссылка недействительна или заменена новой»')

    # ---------- гость с главной и сброс ----------
    print('Заявка гостя с главной и «Сбросить демо»')
    pg.goto(B); pg.wait_for_function("document.querySelector('#statusText').textContent.includes('Демо готово')")
    pg.wait_for_function("document.querySelectorAll('#gApt option').length > 5")
    pg.check('#gEarly'); pg.click('#gBtn'); pg.wait_for_selector('#gRes .ok, #gRes .err')
    check(pg.locator('#gRes .ok').count() == 1, 'гость забронировал и оплатил (с просьбой о раннем заезде): ' + pg.inner_text('#gRes').split('\n')[0][:90])
    check(db("return await p.booking.count({ where: { earlyCheckInStatus: 'requested' } });") >= 2, 'просьба о раннем заезде записана — администратор согласует в «Сегодня»')
    shot('17-guest-request.png')
    with pg.expect_navigation(timeout=30000): pg.click('#reset')
    pg.wait_for_function("document.querySelector('#statusText').textContent.includes('Демо готово')")
    n = db("return await p.repairTask.count({ where: { title: 'Не работает розетка у кровати' } });")
    check(n == 0, '«Сбросить демо» — данные заполнены заново')
    br.close()

print()
print(f'Пройдено проверок: {len(passed)}')
if errors:
    print('Ошибки в консоли браузера:'); print('\n'.join(errors)); sys.exit(1)
print('Ошибок в консоли нет. Скриншоты:', os.path.abspath(OUT))
