# Root-cause regression on static demo. Data and browser contexts are isolated.
# python scripts/systemic-ux-e2e.py URL; CHROME_PATH and SHOTS_DIR override runtime/output.
import os,sys,json
from datetime import date,timedelta
from playwright.sync_api import sync_playwright,expect
B=(sys.argv[1] if len(sys.argv)>1 else 'http://127.0.0.1:8918/').rstrip('/')+'/'
O=os.environ.get('SHOTS_DIR','/private/tmp/sutki-systemic-ux-shots');os.makedirs(O,exist_ok=True)
checks=[];errors=[]
def ok(width,role,name): checks.append({'width':width,'role':role,'check':name});print('PASS',width,role,name,flush=True)
with sync_playwright() as p:
 br=p.chromium.launch(executable_path=os.environ.get('CHROME_PATH','/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'))
 for width in (1280,390):
  for role,name in [('owner','Владелец Азамат'),('admin','Администратор Алина')]:
   ctx=br.new_context(viewport={'width':width,'height':900 if width==1280 else 844},locale='ru-RU',timezone_id='Asia/Almaty');pg=ctx.new_page();pg.on('pageerror',lambda e:errors.append(str(e)));pg.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
   def nav(key,title):
    if width==390:pg.locator('#menuBtn').click()
    pg.locator('#nav [data-nav="'+key+'"]').click();expect(pg.get_by_role('heading',name=title,exact=True)).to_be_visible()
   def close():pg.get_by_role('dialog').get_by_role('button',name='Закрыть',exact=True).click()
   pg.goto(B);expect(pg.locator('#status')).to_contain_text('Демо готово',timeout=60000);pg.locator('#roles .role').filter(has_text=name).click();expect(pg.locator('#userBox')).to_contain_text('Азамат' if role=='owner' else 'Алина');expect(pg.get_by_role('heading',name='Сегодня',exact=True)).to_be_visible()
   assert pg.locator('details.op-sec.blue').count()==1 and not pg.locator('details.op-sec.blue').evaluate('e=>e.open');ok(width,role,'routine grouped, priorities visible')
   pg.get_by_role('button',name='Расписание дня',exact=True).click();expect(pg.locator('.agenda-day')).to_have_count(1);times=pg.locator('.agenda-i .tm').all_text_contents();times=[t for t in times if t];assert times==sorted(times);ok(width,role,'Today → existing chronological single-day schedule');nav('today','Сегодня')
   pg.locator('button.op').filter(has_text='Подготовка просрочена').first.click();expect(pg.get_by_role('dialog')).to_contain_text('Подготовка кв.');assert pg.get_by_role('dialog').locator('a[href^="tel:"]').count()>0;ok(width,role,'known performer phone in context');close()
   pg.locator('.achip').filter(has_text='кв. 7').first.click();expect(pg.get_by_role('dialog')).to_contain_text('Почему не готова');apt_title=pg.get_by_role('dialog').locator('h2').inner_text();bk=pg.locator('#drawer [data-open^="bk:"]').first;bk.click();expect(pg.get_by_role('dialog')).to_contain_text('Бронь №');pg.get_by_role('button',name='← Назад',exact=True).click();expect(pg.get_by_role('dialog').locator('h2')).to_have_text(apt_title);assert len(pg.locator('#drawer [data-open^="bk:"]').all())==1;ok(width,role,'apartment → booking → back; one upcoming booking identity');close()
   conflict=pg.locator('button.op').filter(has_text='ремонт пересекается').first;conflict.click();expect(pg.get_by_role('dialog')).to_contain_text('Статус предложения');pg.get_by_role('button',name='🏠 Квартира: готовность и недочёты',exact=True).click();expect(pg.get_by_role('dialog')).to_contain_text('Работы мастеров');repair=pg.locator('#drawer [data-wr]').filter(has_text='Перенести ремонт');rid=repair.get_attribute('data-wr');repair.click();expect(pg.locator('#repairDate')).to_be_visible();assert pg.get_by_role('dialog').evaluate('e=>e.scrollWidth<=e.clientWidth+1');pg.locator('#repairDate').fill(str(date.today()+timedelta(days=400)));pg.get_by_role('button',name='Перенести ремонт',exact=True).click();expect(pg.locator('#toasts')).to_contain_text('Ремонт перенесён');expect(pg.get_by_role('dialog')).to_contain_text('→');pg.get_by_role('button',name='← Назад',exact=True).click();expect(pg.get_by_role('dialog')).to_contain_text('Работы мастеров');close();expect(pg.locator('#view')).not_to_contain_text('ремонт пересекается с проживанием');ok(width,role,'conflict repaired on same request; fresh origin and Today')
   nav('calendar','Календарь');pg.locator('#calDays').select_option('14');pg.get_by_role('button',name='По дням',exact=True).click();expect(pg.locator('.agenda-day').first).to_be_visible();pg.locator('[data-open^="cl:"]').filter(has_text='не назначена').first.click();expect(pg.locator('#prepAssignee')).to_be_visible();pg.locator('#prepAssignee').select_option(label='Гульнара Ахметова');pg.get_by_role('button',name='Сохранить исполнителя',exact=True).click();expect(pg.get_by_role('dialog').locator('h2')).to_contain_text('Гульнара Ахметова');expect(pg.get_by_role('dialog').locator('.chip').filter(has_text='не назначена')).to_have_count(0);assert pg.get_by_role('dialog').locator('a[href^="tel:"]').count()>0;ok(width,role,'assign preparation → persisted performer/status/contact')
   assert pg.get_by_role('dialog').evaluate('e=>e.scrollWidth<=e.clientWidth+1');pg.screenshot(path=f'{O}/{width}-{role}-assigned.png');close()
   nav('transfers','Трансферы');from_day=pg.locator('#trFrom').input_value();pg.get_by_role('button',name='День →',exact=True).click();expect(pg.locator('#trFrom')).to_have_value(str(date.fromisoformat(from_day)+timedelta(days=1)));expect(pg.locator('#trTo')).to_have_value(str(date.fromisoformat(from_day)+timedelta(days=1)));pg.get_by_role('button',name='← День',exact=True).click();expect(pg.locator('#trFrom')).to_have_value(from_day);pg.locator('#trFrom').fill(str(date.today()-timedelta(days=14)));pg.locator('#trTo').fill(str(date.today()+timedelta(days=14)));pg.get_by_role('button',name='Показать период',exact=True).click();pg.locator('[data-tab="done"]').click();expect(pg.locator('tbody tr').first).to_be_visible();pg.locator('tbody tr').filter(has_text='должны').first.click();expect(pg.get_by_role('dialog')).to_contain_text('Выплата водителю');assert bool(pg.locator('[data-act="paid"]').count())==(role=='owner');ok(width,role,'day/previous/next/range and role-consistent transfer payout');close()
   nav('payouts','Выплаты');expect(pg.locator('#view')).to_contain_text('К оплате');assert bool(pg.locator('#view [data-pay]').count())==(role=='owner');assert bool(pg.locator('#view [data-all]').count())==(role=='owner');ok(width,role,'shared read-only ledger for admin; payment controls only owner')
   if role=='admin':
    statuses=pg.evaluate('''async()=>{let o=[];for(const u of ['/api/admin/payouts/missing/pay','/api/admin/payouts/pay-all','/api/admin/repairs/missing/paid','/api/admin/transfer-jobs/missing/paid'])o.push((await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status);return o}''');assert statuses==[403]*4;ok(width,role,'direct legacy and general payment APIs deny admin')
   else:
    btn=pg.locator('#view [data-pay$=":transfer"]').first;pid=btn.get_attribute('data-pay').split(':')[0];btn.click();expect(pg.locator('#toasts')).to_contain_text('Выплачено');saved=pg.evaluate('''async(id)=>{const r=await fetch('/api/admin/payouts');return (await r.json()).items.find(p=>p.id===id)}''',pid);assert saved['status']=='PAID' and saved['method']=='transfer';ok(width,role,'owner payout saves chosen method and changes state')
   assert not errors,errors;ctx.close()
 br.close()
json.dump({'checks':checks,'consoleErrors':errors},open(O+'/results.json','w'),ensure_ascii=False,indent=2);print('TOTAL',len(checks),'console errors',len(errors))
